import requests, urllib3
urllib3.disable_warnings()
h = {'User-Agent': 'Mozilla/5.0 Chrome/120'}

targets = [
    ('靖西市人民医院', 'www.jxxrmyy.cn'),
    ('钦州市广播电视台', 'www.gxqzxw.com'),
    ('广西大数据发展局', 'dsjfzj.gxzf.gov.cn'),
    ('梧州龙圩区政府', 'www.wzlxq.gov.cn'),
    ('广西自然资源调查监测院', 'www.gxzrzyjc.com'),
    ('广西自然资源调查监测院2', 'www.gxyjch.cn'),
    ('梧州司法局', 'sfj.wuzhou.gov.cn'),
    ('柳州市中医医院', 'www.zhlzy.cn'),
    ('贺州市融媒体中心', 'gxhzxw.com'),
    ('广西科技馆', 'www.gxkjg.com'),
    ('广西标准技术研究院', 'www.gxzl.org.cn'),
    ('崇左市融媒体中心', 'gxcznews.com.cn'),
    ('桂林文旅局', 'wglj.guilin.gov.cn'),
    ('崇左市人民政府', 'www.chongzuo.gov.cn'),
    ('南宁市统计局', 'tj.nanning.gov.cn'),
    ('广西产品质量检验研究院', 'www.gxqt.org.cn'),
    ('全州县人民政府', 'www.glqz.gov.cn'),
    ('百色市人民医院', 'www.gxbssyy.com'),
    ('南宁市行政审批局', 'sp.nanning.gov.cn'),
    ('广西产研院', 'gxiit.cn'),
    ('兴安县人民政府', 'www.xazf.gov.cn'),
    ('玉林市医保局', 'ybj.yulin.gov.cn'),
    ('广西博览局', 'blj.gxzf.gov.cn'),
    ('广西退役军人培训中心', 'www.gxjp.net'),
    ('广西妇女联合会', 'gxwomen.org.cn'),
    ('广西林业局', 'lyj.gxzf.gov.cn'),
    ('玉林市红十字会医院', 'www.yl183.com'),
    ('桂林市林业科学研究所', 'glslykxyjs.com'),
    ('广西妇幼保健院', 'www.gxfybj.com'),
    ('来宾市图书馆', 'www.lbstsg.org.cn'),
    ('百东新区管委会', 'bdxq.baise.gov.cn'),
    ('梧州行政审批局', 'xzspj.wuzhou.gov.cn'),
    ('南宁市人民政府', 'www.nanning.gov.cn'),
    ('广西司法厅', 'sft.gxzf.gov.cn'),
    ('桂林大数据行政审批局', 'xzspj.guilin.gov.cn'),
    ('百色司法局', 'sfj.baise.gov.cn'),
    ('来宾自然资源局', 'lb.dnr.gxzf.gov.cn'),
    ('梧州市政府', 'www.wuzhou.gov.cn'),
    ('防城港住房公积金', 'zfgjj.fcgs.gov.cn'),
    ('梧州自然资源局', 'zrzyj.wuzhou.gov.cn'),
    ('广西信息中心', 'gxxxzx.gxzf.gov.cn'),
    ('广西科协', 'www.gxast.org.cn'),
    ('自治区体育局', 'tyj.gxzf.gov.cn'),
    ('南宁市民政局', 'mzj.nanning.gov.cn'),
    ('自治区应急厅', 'yjglt.gxzf.gov.cn'),
    ('自治区市监局', 'scjdglj.gxzf.gov.cn'),
    ('自治区城乡规划院', 'gxupdi.com'),
    ('南宁市二院', 'nn2yy.com'),
    ('河池市政务服务中心', 'hc.zwfw.gxzf.gov.cn'),
    ('广西政府采购网', 'ccgp-guangxi.gov.cn'),
    ('广西财政厅', 'czt.gxzf.gov.cn'),
    ('广西公共资源交易中心', 'gxggzy.gxzf.gov.cn'),
    ('广西医保局', 'ybj.gxzf.gov.cn'),
    ('钦州市司法局', 'sfj.qinzhou.gov.cn'),
    ('百色住房公积金', 'zfgjj.baise.gov.cn'),
    ('广西教育厅', 'jyt.gxzf.gov.cn'),
    ('柳州市城市管理局', 'csglj.liuzhou.gov.cn'),
    ('南宁消防救援支队', 'www.nn119.com'),
    ('广西中医药大学一附院', 'www.gxzyy.com.cn'),
    ('广西警察学院', 'www.gxjcxy.edu.cn'),
    ('右江民族医学院', 'www.ymcn.edu.cn'),
    ('广西英华国际职业学院', 'www.gxtic.edu.cn'),
    ('广西信息职业技术学院', 'www.gxuie.cn'),
    ('广西农业工程职院', 'www.gxngy.cn'),
    ('防城港职业技术学院', 'www.fcgzy.edu.cn'),
    ('广西师大出版社', 'www.bbtpress.com'),
    ('广西民族大学', 'www.gxun.edu.cn'),
    ('广西希望高中', 'www.gxhhs.net'),
    ('广西职业师范学院', 'www.gxvnu.edu.cn'),
    ('广西水利电力职院', 'www.gxsdxy.cn'),
    ('百色职业学院', 'www.gxbszy.cn'),
    ('广西中医药大学', 'www.gxtcmu.edu.cn'),
    ('广西电力职院', 'www.gxdlxy.com'),
    ('广西农业职业技术大学', 'www.gxnzd.edu.cn'),
    ('广西现代职院', 'www.gxxd.net.cn'),
    ('广西财经学院', 'www.gxufe.edu.cn'),
    ('玉林师范学院', 'www.ylu.edu.cn'),
    ('南宁师范大学', 'www.nnnu.edu.cn'),
    ('广西建设职院', 'www.gxjsxy.cn'),
    ('广西民族大学相思湖学院', 'www.gxxshxy.edu.cn'),
    ('柳州工学院', 'www.lzhit.edu.cn'),
    ('钦州幼儿师专', 'www.qzyz.edu.cn'),
    ('桂林学院', 'www.gxljc.edu.cn'),
    ('广西大学', 'www.gxu.edu.cn'),
    ('广西体育高专', 'www.gxty.edu.cn'),
    ('南宁学院', 'www.nnxy.edu.cn'),
    ('桂林师范学院', 'www.glnc.edu.cn'),
    ('广西安全工程职院', 'www.gxaqzy.cn'),
    ('广西金融职院', 'www.gxjrxy.com'),
    ('贺州学院', 'www.hzxy.edu.cn'),
    ('广西玉林农业学校', 'gxylnx.com'),
    ('广西培贤国际职院', 'www.peixianedu.cn'),
    ('崇左幼儿师专', 'www.czygz.edu.cn'),
    ('广西工商职院', 'www.gxgsxy.edu.cn'),
    ('河池学院', 'www.hcnu.edu.cn'),
    ('柳州职业技术大学', 'www.lzpu.edu.cn'),
    ('桂林理工大学', 'www.glut.edu.cn'),
    ('百色学院', 'www.bsuc.cn'),
    ('北部湾大学', 'www.bbgu.edu.cn'),
    ('广西国际商务职院', 'www.gxibvc.net'),
    ('广西交通职院', 'www.gxjtc.edu.cn'),
    ('广西师范大学', 'www.gxnu.edu.cn'),
    ('广西科技大学', 'www.gxust.edu.cn'),
    ('桂林电子科技大学', 'www.guet.edu.cn'),
    ('广西自然资源职院', 'www.gxnrvtc.edu.cn'),
    ('广西机电职院', 'www.gxcme.edu.cn'),
    ('广西职业技术学院', 'www.gxzjy.edu.cn'),
    ('柳州城市职业学院', 'www.lcvc.edu.cn'),
    ('柳州铁道职院', 'www.ltzy.edu.cn'),
    ('广西工业职院', 'www.gxic.net'),
    ('广西卫生职院', 'www.gxwzy.edu.cn'),
    ('玉林职业技术学院', 'www.gxznzz.com'),
    ('广西智能制造职院', 'www.gxznzz.cn'),
    ('北投信创', 'www.gxbtxc.com'),
    ('广西计算中心', 'www.ccgx.cn'),
    ('广西交通科学研究院', 'www.gxjtkyy.com'),
    ('广西码农信息科技', 'gxcodemaker.com'),
    ('广西金中软件', 'www.kingonsoft.com'),
    ('中国东盟信息港', 'www.caih.com'),
    ('南宁长荣科创', 'gxchr.com'),
    ('数字迈越教育', 'maiyuesoft.com'),
    ('云宝宝大数据', 'cloudbae.cn'),
    ('捷通高速', 'gxetc.com.cn'),
    ('广西路建工程集团', 'www.gxlqjs.com'),
    ('中国电信广西', 'gx.189.cn'),
    ('南宁勘测设计院', 'www.nnkcy.com'),
    ('北部湾大数据交易中心', 'www.bbgdex.com'),
    ('南宁建宁水务', 'www.nnjnwg.com'),
    ('博世科环保', 'www.bossco.cc'),
    ('柳工机械', 'www.liugong.com'),
    ('柳州钢铁', 'www.liuzhousteel.com'),
    ('润建股份', 'runjian.com'),
    ('英腾教育科技', 'yingtengedu.com'),
    ('广西永恒文化', 'www.gxyhtz.com'),
    ('桂林盛才人力', 'www.glrcw.com'),
    ('阳朔遇龙河景区', 'www.ysylh.cn'),
    ('广西农投悦生活', 'www.gxntysh.cn'),
    ('桂林旅游投资', 'www.guilintdc.com'),
    ('桂林两江四湖', 'www.glljsh.com'),
    ('广西耀象文化', 'gxyxsh.com'),
    ('广西卓旭科技', 'www.gxzxkj.com'),
    ('广西靖佳量子', 'www.jjlz.com'),
    ('广西千鼎晟世', 'www.qdsst.com'),
]

alive = 0
dead_list = []
for name, domain in targets:
    ok = False
    for proto in ['https', 'http']:
        for sub in ['', 'www.']:
            try:
                url = proto + '://' + (sub + domain if sub else domain)
                r = requests.get(url, timeout=6, headers=h, verify=False, allow_redirects=True)
                if r.status_code < 500:
                    print('[%d] %-30s %s' % (r.status_code, name, url[:70]))
                    alive += 1
                    ok = True
                    break
            except:
                pass
        if ok:
            break
    if not ok:
        dead_list.append(name)

print()
print('ALIVE: %d | DEAD: %d' % (alive, len(dead_list)))
if dead_list:
    print('DEAD: ' + ', '.join(dead_list))
