"""Tests for the policy snapshot generator/validator (implementation spec 3.7)."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import pytest

from authorized_assessment.runtime import policy_snapshot as ps
from project_paths import policy_snapshot_path


@pytest.fixture(scope="module")
def snapshot() -> dict:
    fixed_now = datetime(2026, 8, 29, tzinfo=timezone.utc)
    return ps.build_policy_snapshot(now=fixed_now)


def test_snapshot_from_real_config_validates(snapshot: dict):
    assert ps.validate_policy_snapshot(snapshot) == []


def test_rate_policy_matches_real_config(snapshot: dict, ):
    exercise = json.loads(Path("gov_exercise_config.json").read_text(encoding="utf-8"))
    rc = exercise["rate_control"]
    rp = snapshot["rate_policy"]
    # 数值必须来自真实配置，不得手造。
    assert rp["same_host_delay_seconds"] == rc["per_host_min_interval_seconds"] == 2.0
    assert rp["same_host_concurrency"] == 1  # ROE.md#2 同 host 串行
    assert rp["cross_host_worker_limit"] == rc["max_concurrency_default"] == 3
    assert rp["jitter_ratio"] == rc["jitter_ratio"]
    assert rp["backoff_status_codes"] == [429, 500, 502, 503, 504]
    assert rp["stop_on_repeated_errors_per_host"] == 5


def test_blocked_and_approval_actions_match_sources(snapshot: dict):
    exercise = json.loads(Path("gov_exercise_config.json").read_text(encoding="utf-8"))
    strategy = json.loads(Path("tool_strategy.json").read_text(encoding="utf-8"))
    assert snapshot["blocked_actions"] == exercise["blocked_actions"]
    assert len(snapshot["blocked_actions"]) == 10
    assert snapshot["approval_required"] == sorted(strategy["approval_gated_phases"].keys())
    assert "credential_testing" in snapshot["approval_required"]


def test_default_posture_is_fail_closed(snapshot: dict):
    assert snapshot["authorization_status"] == "unknown"
    assert snapshot["active_testing_authorized"] is False
    assert snapshot["allowed_actions"] == ["offline_analysis", "readonly_get"]
    assert set(snapshot["stop_conditions"]) == {
        "out_of_scope_asset",
        "service_degradation",
        "waf_alarm",
        "window_closed",
        "operator_stop_request",
    }


def test_source_hashes_are_sha256(snapshot: dict):
    hashes = snapshot["source_hashes"]
    assert set(hashes) == {"gov_exercise_config.json", "tool_strategy.json"}
    for value in hashes.values():
        assert len(value) == 64
        int(value, 16)  # must be hex


def test_no_engagement_or_target_data_by_default(snapshot: dict):
    assert snapshot["engagement_id"] is None
    assert snapshot["workflow"] is None
    assert snapshot["phase"] is None


@pytest.mark.parametrize(
    "mutate, expected_fragment",
    [
        (lambda s: s.pop("rate_policy"), "missing required field: rate_policy"),
        (lambda s: s["rate_policy"].pop("same_host_concurrency"), "same_host_concurrency"),
        (lambda s: s.__setitem__("blocked_actions", []), "blocked_actions"),
        (lambda s: s.__setitem__("active_testing_authorized", "yes"), "must be a boolean"),
        (lambda s: s.__setitem__("authorization_status", "whatever"), "authorization_status"),
        (lambda s: s["rate_policy"].__setitem__("cookie", "x"), "credential-like key"),
        (lambda s: s.setdefault("policy_notes", {}).__setitem__("session_key", "abc"), "credential-like key"),
    ],
)
def test_validator_negatives(snapshot: dict, mutate, expected_fragment: str):
    doc = json.loads(json.dumps(snapshot))
    mutate(doc)
    errors = ps.validate_policy_snapshot(doc)
    assert any(expected_fragment in err for err in errors), errors


def test_write_and_load_roundtrip(snapshot: dict, tmp_path: Path):
    target = tmp_path / "nested" / "policy_snapshot.json"
    written = ps.write_policy_snapshot(snapshot, target)
    assert written == target
    loaded = ps.load_policy_snapshot(target)
    assert loaded == snapshot
    assert ps.validate_policy_snapshot(loaded) == []


def test_write_is_idempotent_bytewise(snapshot: dict, tmp_path: Path):
    # 严格分批逐项验证.md 第十二节第 6 类：重复/幂等例。
    first = tmp_path / "first.json"
    second = tmp_path / "second.json"
    ps.write_policy_snapshot(snapshot, first)
    ps.write_policy_snapshot(snapshot, second)
    assert first.read_bytes() == second.read_bytes()


def test_write_refuses_invalid_snapshot(snapshot: dict, tmp_path: Path):
    bad = dict(snapshot)
    bad.pop("generated_at")
    target = tmp_path / "bad.json"
    with pytest.raises(ValueError, match="refusing to write"):
        ps.write_policy_snapshot(bad, target)
    assert not target.exists()


def test_generated_artifact_on_disk():
    path = policy_snapshot_path()
    assert path.is_file(), "runtime/policy_snapshot.json must be generated by the module"
    loaded = ps.load_policy_snapshot(path)
    assert loaded["schema_version"] == "1.0"
    assert loaded["authorization_status"] == "unknown"
    datetime.fromisoformat(loaded["generated_at"])


def test_project_paths_resolution():
    path = policy_snapshot_path()
    assert path.name == "policy_snapshot.json"
    assert path.parent.name == "runtime"
